basketBallWebSIte/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('users.urls')),
    #    path('main/', include('main.urls')),
#    path('home/', include('main.urls')),
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .views import *
from django.contrib import admin
from .initcmds import *
from django.contrib.auth import views as auth_views

app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', home_page, name='homepage'),
    path('about/', about, name='about'),

    #path('list/players/', ListPlayerView.as_view(), name='list-players'),
    #path('list/teams/', ListTeamView.as_view(), name='list-teams'),
    #path('list/championships/', ListChampionshipView.as_view(), name='list-championships'),
    #path('list/matches', ListMatchView.as_view(), name='list-matches'),

    path('players/<int:pk>/', DetailPlayerView.as_view(), name='player-detail'),
    path('teams/<int:pk>/', DetailTeamView.as_view(), name='team-detail'),
    path('testbase/', test_base, name='test-base'),

    path('create/player/', CreatePlayerView.as_view(), name='create-player'),
    path('add/player/<int:team_id>', add_player, name='add-player'),
    path('update/player/<int:pk>', UpdatePlayerView.as_view(), name='update-player'),
    path('delete/player/<int:pk>/', DeletePlayerView.as_view(), name='delete-player'),

    path('add/coach/<int:team_id>', add_coach, name='add-coach'),
    path('create/coach/', CreateCoachView.as_view(), name='create-coach'),
    path('update/coach/<int:pk>', UpdateCoachView.as_view(), name='update-coach'),
    path('delete/coach/<int:pk>', DeleteCoachView.as_view(), name='delete-coach'),

    path('get_teams/', get_teams, name='get_teams'),

    path('player/search/', player_search, name='player_search'),

    path('create/match/<int:giornata_id>/', create_match, name='create-match'),
    path('update/match/<int:pk>/', UpdateMatchView.as_view(), name='update-match'),
    path('delete/match/<int:pk>/', DeleteMatchView.as_view(), name='delete-match'),
    path('detail/match/<int:pk>', DetailMatchView.as_view(), name='match-detail'),

    path('create/giornate/<int:campionato_id>/', create_giornate, name='create-giornate'),
    path('delete/giornata/<int:pk>/', DeleteGiornataView.as_view(), name='delete-giornata'),

    path('create/champ/', CreateChampView.as_view(), name='create-championship'),
    path('update/champ/<int:pk>', UpdateChampView.as_view(), name='update-championship'),
    path('delete/champ/<int:pk>', DeleteChampView.as_view(), name='delete-championship'),
    path('delete/all/champ/<int:champ_id>', delete_champ_all, name='delete-all-championship'),


    path('create/team/', CreateTeamView.as_view(), name='create-team'),
    path('add/team/<int:campionato_id>', add_team, name='add-team'),
    path('update/team/<int:pk>', UpdateTeamView.as_view(), name='update-team'),
    path('delete/team/<int:pk>', DeleteTeamView.as_view(), name='delete-team'),


    path('create/tabellinoA/<int:match_id>/', create_tabellinoA, name='create-tabellinoA'),
    path('create/nuovo/tabellinoA/<int:match_id>/', create_nuovo_tabellinoA, name='create-nuovo-tabellinoA'),
    path('create/tabellinoB/<int:match_id>/', create_tabellinoB, name='create-tabellinoB'),
    path('create/nuovo/tabellinoB/<int:match_id>/', create_nuovo_tabellinoB, name='create-nuovo-tabellinoB'),
    path('delete/tabellino/<int:pk>', DeleteTabellinoView.as_view(), name='delete-tabellino'),

    path('detail/campionato/<int:pk>', DetailCalendarioView.as_view(), name='detail-calendario'),
    path('dashboard/', dashboard_view, name='dashboard'),

    path('add/comment/<int:match_id>', add_comment, name='add-comment'),
    path('delete/commento/<int:comment_id>/', delete_comment, name='delete-comment'),
    path('like-comment/', like_comment, name='like-comment'),
    path('dislike-comment/', dislike_comment, name='dislike-comment'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

check_stats()

# erase_db()
# init_db()

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import Group
from django.forms import widgets
from .models import *


class PlayerSearchForm(forms.Form):
    last_name = forms.CharField(label="Cognome", max_length=100, required=False)
    name = forms.CharField(label="Nome", max_length=100, required=False)
    championship = forms.ChoiceField(label='Campionato', choices=[], required=False)
    team = forms.ChoiceField(label='Squadra', choices=[], required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['championship'].choices = self.get_championship_choices()
        self.fields['team'].choices = self.get_team_choices()

    def get_championship_choices(self):
        championships = ChampionShip.objects.all()
        choices = [('', 'Tutti i Campionati')]
        choices += [(championship.id, championship.name) for championship in championships]
        return choices

    def get_team_choices(self):
        teams = Team.objects.all()
        choices = [('', 'Tutte le Squadre')]
        choices += [(team.id, team.name) for team in teams]
        return choices


class CreateMatchForm(forms.ModelForm):
    date = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))

    def clean(self):
        if self.cleaned_data['teamA'] == self.cleaned_data['teamB']:
            self.add_error("teamB", "Non può giocare con sè stessa")

        return self.cleaned_data

    class Meta:
        model = Match
        fields = ['date', 'teamA', 'teamB', 'location']


class AddPlayerForm(forms.ModelForm):
    birth_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = Player
        fields = ['name', 'last_name', 'number', 'role', 'birth_date', 'profile_img']


class AddCoachForm(forms.ModelForm):
    birth_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = Player
        fields = ['name', 'last_name', 'birth_date', 'profile_img']


class AddTeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ['name', 'city', 'img', 'main_sponsor']


class CreateTabellinoForm(forms.ModelForm):

    def clean(self):
        pass

    class Meta:
        model = Tabellino
        fields = '__all__'

main/views.py
import datetime

from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from django.db.models import Q
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponseForbidden
from django.urls import reverse_lazy, reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST, require_GET
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from .models import *
from .forms import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.mixins import UserPassesTestMixin
from django.utils import timezone
from django.contrib import messages


def about(request):
    return render(request, 'about.html')


def home_page(request):
    if request.GET.get('login') == 'ok':
        return render(request, 'home_page.html', context={'benvenuto': request.user.username})
    if request.GET.get('logout') == 'ok':
        return render(request, 'registration/prova.html')
    return render(request, 'home_page.html')


@user_passes_test(lambda u: u.is_staff)
def test_base(request):
    return render(request, 'base.html')


########################################################################################################################
# Retrieve functions
@require_GET
def get_teams(request):
    championship = request.GET.get('championship')
    if championship == '':
        teams = Team.objects.all()
    elif championship:
        teams = Team.objects.filter(championships_id__exact=championship)
    else:
        teams = Team.objects.none()

    team_data = [{'id': '', 'name': 'Tutte le Squadre'}] + [{'id': team.id, 'name': team.name} for team in teams]

    return JsonResponse({'teams': team_data})


# Actual views

def player_search(request):
    players = Player.objects.all()

    if request.method == 'POST':
        form = PlayerSearchForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            last_name = form.cleaned_data.get('last_name')
            team = form.cleaned_data.get('team')
            championship = form.cleaned_data.get('championship')

            if championship != '':
                form.fields['team'].choices = [('', 'Tutte le Squadre')]
                teams = Team.objects.filter(championships_id__exact=championship)
                form.fields['team'].choices += [(team.id, team.name) for team in teams]
                players = players.filter(team__in=ChampionShip.objects.get(pk=championship).teams.all())
            if team != '':
                players = players.filter(team__exact=team)
            if name:
                players = players.filter(name__istartswith=name)
            if last_name:
                players = players.filter(last_name__istartswith=last_name)

    else:
        form = PlayerSearchForm()

    context = {'form': form,
               'players': players,
               }
    return render(request, 'player_search.html', context)


########################################################################################################################
# Player


class ListPlayerView(ListView):
    model = Player
    template_name = 'list_player.html'


class DetailPlayerView(DetailView):
    model = Player
    template_name = 'detail_player.html'
    context_object_name = 'giocatore'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        points, rebounds, assists = self.get_object().get_total_points()
        counter = self.get_object().get_total_matches()

        partite_in_casa, partite_in_casa_giocate = self.get_object().get_partite_in_casa()
        partite_in_trasferta, partite_in_trasferta_giocate = self.get_object().get_partite_in_trasferta()

        ctx['media_punti'] = round(points / counter, 2) if counter != 0 else 0
        ctx['media_rimbalzi'] = round(rebounds / counter, 2) if counter != 0 else 0
        ctx['media_assist'] = round(assists / counter, 2) if counter != 0 else 0
        ctx['points'] = points
        ctx['rebounds'] = rebounds
        ctx['blocks'] = assists
        ctx['partite_in_casa'] = partite_in_casa
        ctx['partite_in_casa_giocate'] = partite_in_casa_giocate
        ctx['partite_in_trasferta'] = partite_in_trasferta
        ctx['partite_in_trasferta_giocate'] = partite_in_trasferta_giocate
        ctx['partite'] = self.object.get_partite()
        return ctx


class DeletePlayerView(UserPassesTestMixin, DeleteView):
    model = Player
    template_name = 'delete_player.html'
    success_url = reverse_lazy('main:dashboard')
    context_object_name = 'player'

    def test_func(self):
        return self.request.user.is_staff


class UpdatePlayerView(UserPassesTestMixin, UpdateView):
    model = Player
    fields = '__all__'
    template_name = 'update_player.html'

    def get_success_url(self):
        return reverse_lazy('main:player-detail', args=[self.object.pk])

    def test_func(self):
        return self.request.user.is_staff


class CreatePlayerView(UserPassesTestMixin, CreateView):
    model = Player
    fields = '__all__'
    success_url = reverse_lazy('main:dashboard')
    template_name = 'create_player.html'

    def test_func(self):
        return self.request.user.is_staff


@user_passes_test(lambda u: u.is_staff)
def add_player(request, team_id):
    if request.method == 'POST':
        form = AddPlayerForm(request.POST)
        if form.is_valid():
            player = Player(team_id=team_id)
            player.name = form.cleaned_data.get('name')
            player.last_name = form.cleaned_data.get('last_name')
            player.number = form.cleaned_data.get('number')
            player.role = form.cleaned_data.get('role')
            player.birth_date = form.cleaned_data.get('birth_date')
            player.profile_img = form.cleaned_data.get('profile_img')

            player.save()

            return redirect('main:dashboard')
        else:
            return render(request, 'add_player.html', context={'form': form})
    else:
        form = AddPlayerForm()

        return render(request, 'add_player.html', context={'form': form, 'squadra': Team.objects.get(pk=team_id)})


##################################################################################################################
# Coach


class DeleteCoachView(UserPassesTestMixin, DeleteView):
    model = Coach
    template_name = 'delete_coach.html'
    success_url = reverse_lazy('main:dashboard')
    context_object_name = 'coach'

    def test_func(self):
        return self.request.user.is_staff


class UpdateCoachView(UserPassesTestMixin, UpdateView):
    model = Coach
    fields = '__all__'
    template_name = 'update_coach.html'
    context_object_name = 'coach'

    def get_success_url(self):
        return reverse_lazy('main:dashboard')

    def test_func(self):
        return self.request.user.is_staff


class CreateCoachView(UserPassesTestMixin, CreateView):
    model = Coach
    fields = '__all__'
    success_url = reverse_lazy('main:dashboard')
    template_name = 'create_coach.html'

    def test_func(self):
        return self.request.user.is_staff


@user_passes_test(lambda u: u.is_staff)
def add_coach(request, team_id):
    if request.method == 'POST':
        form = AddCoachForm(request.POST)
        if form.is_valid():
            coach = Coach(team_id=team_id)
            coach.name = form.cleaned_data.get('name')
            coach.last_name = form.cleaned_data.get('last_name')
            coach.birth_date = form.cleaned_data.get('birth_date')
            coach.profile_img = form.cleaned_data.get('profile_img')

            coach.save()

            return redirect('main:dashboard')
        else:
            return render(request, 'add_coach.html', context={'form': form})
    else:
        form = AddCoachForm()

        return render(request, 'add_coach.html', context={'form': form, 'squadra': Team.objects.get(pk=team_id)})


########################################################################################################################
# Teams

class DeleteTeamView(UserPassesTestMixin, DeleteView):
    model = Team
    template_name = 'delete_team.html'
    success_url = reverse_lazy('main:dashboard')

    def test_func(self):
        return self.request.user.is_staff

class UpdateTeamView(UserPassesTestMixin, UpdateView):
    model = Team
    fields = '__all__'
    template_name = 'update_team.html'
    success_url = reverse_lazy('main:dashboard')

    def test_func(self):
        return self.request.user.is_staff

class CreateTeamView(UserPassesTestMixin, CreateView):
    model = Team
    fields = '__all__'
    template_name = 'create_team.html'
    success_url = reverse_lazy('main:dashboard')

    def test_func(self):
        return self.request.user.is_staff


@user_passes_test(lambda u: u.is_staff)
def add_team(request, campionato_id):
    if request.method == 'POST':
        form = AddTeamForm(request.POST)
        if form.is_valid():
            team = Team(championships_id=campionato_id)
            team.name = form.cleaned_data.get('name')
            team.city = form.cleaned_data.get('city')
            team.main_sponsor = form.cleaned_data.get('main_sponsor')
            team.img = form.cleaned_data.get('img')

            team.save()

            return redirect('main:dashboard')
        else:
            return render(request, 'add_team.html',
                          context={'form': form, 'campionato': ChampionShip.objects.get(pk=campionato_id)})
    else:
        form = AddTeamForm()

        return render(request, 'add_team.html',
                      context={'form': form, 'campionato': ChampionShip.objects.get(pk=campionato_id)})


class ListTeamView(ListView):
    model = Team

main/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}About{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h1 class="mb-4">Benvenuto sul "Portale FIP"</h1>
            <p>Questo sito è fatto da me Marco Morini, per l'esame di Tecnologie Web dell'Università degli Studi di Modena e Reggio Emilia tenuto dalla professoressa Claudia Canali e Nicola Capodieci</p>
            <p>È stato creato puramente a scopo didattico per mettere in pratica gli insegnamenti forniti dai docenti del corso sopra citati durante le lezioni.</p>
            <p>Questo sito ha lo scopo di rendere disponibili a tutti i risultati delle partite dei campionati di più alta categoria italiani.</p>
            <p>Potrai scoprire i risultati di tutte le partite disputate e le statistiche dei giocatori durante la stagione.</p>
    </div>
</div>
{% endblock %}

main/templates/add_coach.html
{% extends 'base.html' %}


{% block title %}Creazione Allenatore{% endblock %}


{% block content %}
  <div class="container">
    <a href="{% url 'main:dashboard' %}" class="btn btn-primary">Torna alla Dashboard</a>
    <h2>Aggiungi un nuovo allenatore a {{ squadra }}</h2>
    <form method="post" class="row g-3">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="col-12">
        <button type="submit" class="btn btn-primary">Aggiungi</button>
      </div>
    </form>
  </div>
{% endblock %}

main/templates/create_champ.html
{% extends 'base.html' %}


{% block title %}Creazione Campionato{% endblock %}


{% block content %}
  <div class="container">
    <a href="{% url 'main:dashboard' %}" class="btn btn-primary" style="margin-bottom: 50px">Torna alla Dashboard</a>
    <form method="post" class="row g-3">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="col-12">
        <button type="submit" class="btn btn-primary">Aggiungi</button>
      </div>
    </form>
  </div>
{% endblock %}

main/templates/create_match.html
{% extends 'base.html' %}


{% block content %}
    <h2>Aggiungi Partita alla {{ giornata.num }}° giornata di {{ giornata.calendario }}</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Crea</button>
    </form>
{% endblock %}

main/templates/create_tabellinoA.html
{%  extends 'create_tabellino.html' %}


{% block url %}{%  url 'main:create-tabellinoA' match_id %}{% endblock %}

main/templates/create_tabellinoB.html
{%  extends 'create_tabellino.html' %}

{% block url %}{%  url 'main:create-tabellinoB' match_id %}{% endblock %}

main/templates/delete_coach.html
{% extends 'base.html' %}

{% block title %} Elimina Allenatore {% endblock %}

{% block content %}
    <a href="{% url 'main:dashboard' %}" class="btn btn-primary" style="margin-bottom: 50px">Torna alla Dashboard</a>
    <h3>Vuoi eliminare l'allenatore: {{ coach.name }} {{ coach.last_name }}??</h3>
    <form method="post" action="{% url 'main:delete-coach' coach.pk %}">
        {% csrf_token %}
        <button type="submit">Cancella</button>
    </form>
{% endblock %}

main/templates/delete_match.html
{% extends 'base.html' %}

{% block title %}
Cancella Partita
{% endblock %}

{% block content %}
    <a href="{% url 'main:dashboard' %}" class="btn btn-primary" style="margin-bottom: 50px">Torna alla Dashboard</a>
    <h3>Vuoi eliminare la partita:{{ match.teamA }} - {{ match.teamB }}??</h3>
    <form method="post" action="{% url 'main:delete-match' match.pk %}">
        {% csrf_token %}
        <button type="submit">Cancella</button>
    </form>
{% endblock %}

main/templates/delete_tabellino.html
{% extends 'base.html' %}

{% block title %}
Cancella Tabellino
{% endblock %}

{% block content %}
    <h3>Vuoi eliminare il tabellino della partita:{{ partita.teamA }} - {{ partita.teamB }}??</h3>
    <form method="post" action="{% url 'main:delete-tabellino' tabellino.pk %}">
        {% csrf_token %}
        <button type="submit">Cancella</button>
    </form>
{% endblock %}

main/templates/detail_player.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ giocatore }}{% endblock %}

{% block styles %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-body">
                        <div class="text-center mb-4">
                            {% if giocatore.profile_img %}
                                <img src="{{ giocatore.profile_img.url }}" alt="Profilo"
                                     class="img-fluid rounded-circle w-50">
                            {% else %}
                                <img src="{% static 'img/no-profile-picture-icon-1.jpg' %}" alt="Profilo"
                                     class="img-fluid rounded-circle w-50">
                            {% endif %}
                        </div>
                        <h2 class="card-title text-center">{{ giocatore.name }} {{ giocatore.last_name }}</h2>
                        <p class="card-text text-center"><strong>Ruolo:</strong> {{ giocatore.role }}</p>
                        <p class="card-text text-center"><strong>Data di nascita:</strong> {{ giocatore.birth_date }}
                        </p>
                        <p class="card-text text-center"><strong>Numero di maglia:</strong> {{ giocatore.number }}</p>
                        <p class="card-text text-center"><strong>Squadra:</strong><a
                                href="{% url 'main:team-detail' giocatore.team.pk %}"> {{ giocatore.team }}</a></p>
                    </div>
                </div>
            </div>

            <canvas id="statisticheGrafico"></canvas>


            <div class="card mt-auto">
                <div class="card-body">
                    <h3 class="card-title text-primary">Statistiche</h3>
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">Partita</th>
                            <th scope="col">Punti</th>
                            <th scope="col">Rimbalzi</th>
                            <th scope="col">Assist</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for partita in partite %}
                            <tr>
                                {% if partita in partite_in_casa %}
                                    <td>
                                        <a href="{% url 'main:match-detail' partita.pk %}"> {{ partita.teamB.name }}</a>[{{ partita.pointsA }}-{{ partita.pointsB }}]
                                    </td>
                                    {% if partita in partite_in_casa_giocate %}
                                        {% for stat in partita.tabellinoA.get_stats %}
                                            {% if giocatore == stat.player %}
                                                {% if stat.points %}
                                                    <td>{{ stat.points }}</td>
                                                {% else %}
                                                    <td>0</td>
                                                {% endif %}
                                                {% if stat.rebounds %}
                                                    <td>{{ stat.rebounds }}</td>
                                                {% else %}
                                                    <td>0</td>
                                                {% endif %}
                                                {% if stat.blocks %}
                                                    <td>{{ stat.blocks }}</td>
                                                {% else %}
                                                    <td>0</td>
                                                {% endif %}
                                            {% endif %}
                                        {% endfor %}
                                    {% else %}
                                        <td>-</td>
                                        <td>-</td>
                                        <td>-</td>
                                    {% endif %}
                                {% else %}
                                    <td>
                                        <a href="{% url 'main:match-detail' partita.pk %}"> {{ partita.teamA.name }}</a>[{{ partita.pointsA }}-{{ partita.pointsB }}]
                                    </td>
                                    {% if partita in partite_in_trasferta_giocate %}
                                        {% for stat in partita.tabellinoB.get_stats %}
                                            {% if giocatore == stat.player %}
                                                {% if stat.points %}
                                                    <td>{{ stat.points }}</td>
                                                {% else %}
                                                    <td>0</td>
                                                {% endif %}
                                                {% if stat.rebounds %}
                                                    <td>{{ stat.rebounds }}</td>
                                                {% else %}
                                                    <td>0</td>
                                                {% endif %}
                                                {% if stat.blocks %}
                                                    <td>{{ stat.blocks }}</td>
                                                {% else %}
                                                    <td>0</td>
                                                {% endif %}
                                            {% endif %}
                                        {% endfor %}
                                    {% else %}
                                        <td>-</td>
                                        <td>-</td>
                                        <td>-</td>
                                    {% endif %}
                                {% endif %}
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="2">Nessuna partita registrata.</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% if partite %}
                        <div class="text-center">
                            <p class="card-text"><strong>Media punti:</strong> {{ media_punti }}</p>
                            <p class="card-text"><strong>Media rimbalzi:</strong> {{ media_rimbalzi }}</p>
                            <p class="card-text"><strong>Media assist:</strong> {{ media_assist }}</p>
                        </div>
                    {% else %}
                        <p class="card-text text-center">Nessuna partita registrata per calcolare le medie.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        // Raccolta dati delle statistiche dalla variabile 'partite'
        var puntiData = [];
        var rimbalziData = [];
        var assistData = [];
        var partiteLabels = [];

        {% for partita in partite %}
            {% if partita in partite_in_casa %}
                {% if partita in partite_in_casa_giocate %}
                    {% for stat in partita.tabellinoA.get_stats %}
                        {% if giocatore == stat.player %}
                            puntiData.push({{ stat.points }});
                            rimbalziData.push({{ stat.rebounds }});
                            assistData.push({{ stat.blocks }});
                            partiteLabels.push("{{ partita.teamB.name }}({{ partita.date.day }}/{{ partita.date.month }})");
                        {% endif %}
                    {% endfor %}
                {% else %}
                    puntiData.push(0);
                    rimbalziData.push(0);
                    assistData.push(0);
                {% endif %}
            {% else %}
                {% if partita in partite_in_trasferta_giocate %}
                    {% for stat in partita.tabellinoB.get_stats %}
                        {% if giocatore == stat.player %}
                            puntiData.push({{ stat.points }});
                            rimbalziData.push({{ stat.rebounds }});
                            assistData.push({{ stat.blocks }});
                            partiteLabels.push("{{ partita.teamA.name }}({{ partita.date.day }}/{{ partita.date.month }})");
                        {% endif %}
                    {% endfor %}
                {% else %}
                    puntiData.push(0);
                    rimbalziData.push(0);
                    assistData.push(0);
                {% endif %}
            {% endif %}
        {% endfor %}

        // Configurazione grafico
        var ctx = document.getElementById('statisticheGrafico').getContext('2d');
        var chart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: partiteLabels,
                datasets: [{
                    label: 'Punti',
                    data: puntiData,
                    backgroundColor: 'rgba(75, 192, 192, 0.5)',
                    borderColor: 'rgba(75, 192, 192, 1)',
                    borderWidth: 1
                }, {
                    label: 'Rimbalzi',
                    data: rimbalziData,
                    backgroundColor: 'rgba(255, 99, 132, 0.5)',
                    borderColor: 'rgba(255, 99, 132, 1)',
                    borderWidth: 1
                }, {
                    label: 'Assist',
                    data: assistData,
                    backgroundColor: 'rgba(54, 162, 235, 0.5)',
                    borderColor: 'rgba(54, 162, 235, 1)',
                    borderWidth: 1
                }]
            },
            options: {
                responsive: true,
                scales: {
                    x: {
                        grid: {
                            display: false
                        }
                    },
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    </script>
{% endblock %}

main/templates/list_matches.html
{% extends 'base.html' %}

{% block content %}
    {% for partita in partite %}
        <a href={%  url 'main:match-detail' partita.id %}> {{ partita }}</a>
    {% endfor %}
{% endblock %}